eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9400/eureka/
  instance: 
    hostname: ${spring.cloud.client.ipAddress}
server:
  port: 9700
management:
  security:
    enabled: false
spring:
 application:
  name: platform-zuul
 cloud:
  config:
   label: master
   profile: dev
   #uri: http://192.168.18.140:9500
   discovery:
    enabled: true
    serviceId: PLATFORM-CONFIG-SERVER
  loadbalancer:
   retry:
    enabled: true
 rabbitmq:
    host: 192.168.1.121
    port: 5672
    username: rabbitadmin
    password: 123456
 redis:
    host: 192.168.1.121
    port: 6379
    timeout: 20000
 session:
    store-type: redis
zuul:
  add-host-header: true
  #是否开启重试功能
  retryable: true
  sensitiveHeaders: 
#  routes:
#    user:
#      path: /user/**
#      serviceId: PLATFORM-USER
#      sensitiveHeaders: 
#    inter:
#      path: /inter/**
#      serviceId: PLATFORM-INTERFACE
#      sensitiveHeaders: 
#    case:
#      path: /case/**
#      serviceId: PLATFORM-TESTCASE
#      sensitiveHeaders: 
#    group:
#      path: /group/**
#      serviceId: PLATFORM-TESTGROUP
#      sensitiveHeaders: 
#    mock:
#      path: /mock/**
#      serviceId: PLATFORM-THIRDPARTYMOCK
#      sensitiveHeaders: 
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  #对当前服务的重试次数
  MaxAutoRetries: 2
  #切换相同Server的次数
  MaxAutoRetriesNextServer: 1
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
ignore:
  urlPath: /platform-user/user/getUserBySession, /platform-user/user/login, platform-user/user/logout, /zuul/initURLMap, /info